/* Same as youtube categories (subset)*/
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (1, "Film & Animation")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (2, "Gaming")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (3, "Music")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (4, "Pets & Animals")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (5, "People")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (6, "Comedy")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (7, "News & Politics")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (8, "Entertainment")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (9, "Autos & Vehicles")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (10, "Education")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (11, "Activism")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (12, "Sports")
INSERT OR IGNORE INTO VIDEO_TAG(id, name) VALUES (13, "World & Travel")